*PART

         1         1         1         0         1         0         0         0
*PART

         2         2         2         0         0         0         0         0
*PART
$      pid       sid       mid     eosid      hgid    adpopt
Rubber
         1         1         1
$
$
*PART
$      pid       sid       mid     eosid      hgid    adpopt
plate
         1         1         1
plate-tip
         2         1         1
wall
         3         1         1
$
$
*PART

         1         1         1         0         0
*PART

         2         2         2         0         0
